const ERRORS = {
    VALIDATION: 'ERROR_VALIDATION',
    INCORRECT_EMAIL_OR_PASSWORD: 'INCORRECT_EMAIL_OR_PASSWORD',
    INVALID_RESET_PASSWORD_TOKEN: 'INVALID_RESET_PASSWORD_TOKEN',
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
    SERVER_ERROR: 'SERVER_ERROR',
    NOT_FOUND: 'NOT_FOUND'
};

module.exports = ERRORS;
