const ERRORS = {
    VALIDATION: 'ERROR_VALIDATION',
    INCORRECT_EMAIL_OR_PASSWORD: 'INCORRECT_EMAIL_OR_PASSWORD',
    INVALID_RESET_PASSWORD_TOKEN: 'INVALID_RESET_PASSWORD_TOKEN'
};

module.exports = {
    ERRORS
};
