const SUCCESS = {
    RESET_PASSWORD_TOKEN_GENERATED_SUCCESSFULLY: 'RESET_PASSWORD_TOKEN_GENERATED_SUCCESSFULLY',
    PASWORD_UPDATED_SUCCESSFULLY: 'PASWORD_UPDATED_SUCCESSFULLY'
};

module.exports = SUCCESS;
