const VALIDATION_RULES = {
    REQUIRED: 'REQUIRED',
    NOT_EMAIL: 'NOT_EMAIL',
    FORMAT: 'FORMAT',
    PASSWORDS_ARE_NOT_EQUAL: 'PASSWORDS_ARE_NOT_EQUAL',
    UNIQUE: 'UNIQUE',
    MIN_LENGTH: 'MIN_LENGTH'
};

module.exports = {
    VALIDATION_RULES
};
